name: Rust

on:
  push:
    # branches: [ "master", "dev" ]
    branches: [ '*' ] # test
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make docker-build
    # Tag that will be automatically picked by ncipollo/release-action.
    - name: Tag
      run: |-
        tag_name="$(date +%y%m%d)-$(git rev-parse HEAD | head -c 7)"
        echo "tag_name=${tag_name}" | tee -a "$GITHUB_OUTPUT"
    # https://github.com/ncipollo/release-action.
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/raptor-cage.tgz,dist/raptor-cage.sha256"
        tag: ${{ steps.Tag.outputs.tag_name }}
