name: Rust

on:
  push:
    # branches: [ "master", "dev" ]
    branches: [ '*' ] # test
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make docker-build
    # Tag that will be automatically picked by ncipollo/release-action.
    - name: Generate Tag
      id: tag_step
      run: |-
        program_version="$(echo 1.0.0)"
        tag_name="${program_version}-$(date +%y%m%d%H%M)-$(git rev-parse HEAD | head -c 7)"
        printf "tag_name=${tag_name}\nprogram_version=${program_version}\n" | tee -a "$GITHUB_OUTPUT"
    # https://github.com/ncipollo/release-action.
    - uses: ncipollo/release-action@v1
      id: release_step
      with:
        artifacts: "dist/raptor-cage.tgz,dist/raptor-cage.sha256"
        tag: ${{ steps.tag_step.outputs.tag_name }}
        makeLatest: true
    - name: Publish to the AUR
      run: |-
        echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> ~/.ssh/known_hosts
        git clone https://aur.archlinux.org/raptor-cage-bin.git
        
