name: Rust

on:
  push:
    # branches: [ "master", "dev" ]
    branches: [ '*' ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release
