name: Rust

on:
  push:
    # branches: [ "master", "dev" ]
    branches: [ '*' ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make docker-build
    # https://github.com/ncipollo/release-action.
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/raptor-cage.tgz,dist/raptor-cage.sha256"
        tag: "1.0.0"
